### ISSUE TITLE
Version 2.0.0 milestone goals

### ISSUE THREAD

**Issue by calebmsword** [calebmsword/clone-deep#35]
Implemented in [PR 37](https://github.com/calebmsword/clone-deep/pull/37):
- [x] **Remove length restriction on variable names. There are too many cases where 1-letter names are useful**
- [x] **Update .npmignore for the new scripts directory**
- [x] **Separate handleTag into handleNativeClasses and handleSyncWebAPIs**
- [x] ~~**Update isTypedArray so it queries for method available in original ES6 specification**~~ It was fine how it was, no need to change it.
- [x] **Add smoke tests for index.js to ensure it exports necessary functions**
- [x] **Create promise-based mode**
  - Allow cloneDeep and cloneDeepFully to optionally run asynchronously (return the clone in a promise)
  - Allow customizers and cloning methods to behave asynchronously as well
- [x] **Support promise-based web apis**
  - The excluded Web APIs not currently supported can only be created through global functions which return promises containing the instance. Hence we cannot support all Web APIs until we can run cloneDeep asynchronously.
  - Add a new method to handleTag: handleAsyncWebAPIs and implement the functionality there.

~~Next PR should handle all of the following~~ Implemented in [PR 38](https://github.com/calebmsword/clone-deep/pull/37):
- [x] **Refactor `instanceof` usages**
  - See my notes on `instanceof` in my javascript-notes repository. Use a variation of `isInstance` function from there in place of all `instanceof` uses. Consider return an object containing the verified value and a boolean if you can find a way to make the returned value typed as an instance of the constuctor with some TypeScript jank.
- [x] **Complete JSDoc annotations**
  - Many function arguments and some functions don't have descriptions and only have type annotations. All parameters and functions should have descriptions.
  - Comments should be provided for all symbols in .d.ts files.
  - Indent module annotations in cms-clone-deep.d.ts.
- [x] **Update createFileList so it is robust in the same manner as core-js's implementation**
  - The person I credited actually copied core-js's approach to createFileList. So just copy the implementation done by that person.
- [x] **Create new functions cloneDeepAsync and cloneDeepFullyAsync. Do not allow cloneDeep/cloneDeepFully to run asynchronously. (If you can figure out a way to get TypeScript to know whether the return is a promise or not, then don't worry about it.)**
  - I want this because the return value of cloneDeep is a mess right now since it can return a clone or a promise containing the clone. It will be easier to use in practice if we make the return value an atomic type.
- [x] **CloneDeep/CloneDeepFully/etc should only take a config. You should not be able to pass a function as the customizer.**
  - This is too niche of a use case to justify all the additional complications overloading this parameter provides. 
- [x] **Customizers and cloning methods should be able to ignore prototypes and properties without providing an explicit clone**
- [x] **Customizers and cloning methods should be able to cause the algorithm to throw independent of `letCustomizerThrow` option**

The rest of these should each be their own individual PR:
- [x] **Support Node Buffer type**
  - This is very simple, so just tack it onto some other task.
- [x] **Update the benchmarking UI**
  - add timers for lodash's, es-toolkit's, and clone's (using circular & non-enumerable) performance
  - add checkboxes to run in various performance modifiers dynamically
  - add secondary box to benchmark cloneDeepFully (do not compare to clone)
     - create an input field to determine the number of (method-less) prototypes to clone
- [x] **Add more ways to opt into better performance**
  - ignoreCircularReferences
  - ignoreDescriptors
  - ignoreMetadata
  - fastTypeChecking
    - explore using `instanceof` instead of tags to type-check things in fastTypeChecking mode. My experiments suggest that it is considerably faster this way.
- [x] **Update logger**
  - [x] Allow the logger to receive strings or error objects.
  - [x] ~~Remove CloneDeepWarning and use simple strings instead. Throw errors if uncaught errors are found~~. I left it the way it is. It works and it's not a big problem.
  - [x] Remove logMode quiet mode. Add a new logConfig object to cloneDeep and cloneDeepFully. Allow the user to specify exactly which "clone smells" can and can't be logged.
  - [x] Stop throwing warnings on Promises. There's no point in doing so.
- [x] **Create transpiled versions of this package**
  - create ES6, ES6 minified, ES5, ES5 minified packages using babel (we need a bundler like rollup, actually). Make all of these npm packages as well.
- [x] **Double-check robust type-checking**
  - review ECMAScript and HTML specifications to ensure that methods are specified to throw as expected
  - research what happens when instances have their prototypes changed, but you still call use the robust approach on those instances. Check this in Firefox and Chrome
- [x] **Rehaul documentation**
     - add changelog to README
     - create Docs folder
       - create with examples for useful customizers
       - create file with API documentation
     - link to Docs files on github repo in JSDoc annotations for exported functions for this package
     - VASTLY overhaul the issue and feature request templates in .github

## Nice-to-haves:
- [ ] **Reimplement CloneDeepFully**
  - CloneDeepFully only clones the chain of the provided object. Nested objects with non-null prototypes will not be fully cloned.
- [ ] **Reorganize application state**
  - [x] Instead of passing value, prop, parentOrAssigner, and metadata around, just passed the queueItem object from the for loop in processQueue.
  - [x] create an object cloneGlobals with properties containing the container, log, queue, and pendingResult objects and pass this around all the functions.
  - [x] ~~Instead of declaring variables in processQueue, create a class `QueueItemStatus` that contains the status of the clone of a particular value. Create methods which modify the state based on results from handleCustomizer, handleCloningMethods, handleNativeTypes, etc.~~ This would overcomplicate things. Implementing the previous two points solved my problems (mostly).
  - [x] Only pass queueItem, cloneGlobals, ~~and queueItemStatus~~ to each function internally.
  - [ ] Consider creating two functions getGlobal and setGlobal. Instead of drilling globalState throughout all the functions, just have functions which use the global state call getGlobal.

**Comment by calebmsword** [comment]
In regards to the benchmark UI updates:

How to get lodash from CDN in web worker:
import('https://cdn.jsdelivr.net/npm/lodash@4.17.21/+esm')

Clone CDN:
https://cdn.jsdelivr.net/npm/clone@2.1.1/clone.min.js

es-toolkit CDN:
https://es-toolkit.slash.page/usage.html#browsers

**Comment by calebmsword** [comment]
The [recent PR](https://github.com/calebmsword/clone-deep/pull/41) implemented this issue.
